---
title: "Prolactin/Receptor Data"
author: "Victoria"
date: "10/16/2018"
output: html_document
---

```{r data, include=FALSE}
library(tidyverse)
library(officer)#creates Ppt slides
library(rvg)#sends ggplot to ppt
library(lsmeans)

prl<-read.csv(file="~/Documents/lab/PRL_PRLR_RNAseq_data.csv")

prl.long<-prl %>% gather(key="bird",value = "counts",4:991, factor_key = TRUE) #wide to long
prl.long$TranscriptID<-NULL #removes meaningless columns
prl.long$Num<-NULL 
prl.long<-separate(data = prl.long, col = bird, into = c("bird_id", "sex", "tissue","stage"), sep = "_") #splits bird details into separate columns by _ separator
prl.long$counts<-as.numeric(prl.long$counts)
prl.long$stage<-as.factor(prl.long$stage)
prl.long$manip <- ifelse(grepl("m", prl.long$stage), "y", "n") #y = yes, manipulation ; n=no,not a manip, a characterization

prl.long$stage <- factor(prl.long$stage, levels=c("control", "bldg", "lay", "inc.d3", "m.inc.d3","inc.d9", "m.inc.d8", "m.inc.d9", "inc.d17", "m.inc.d17", "hatch", "extend", "extend.hatch", "prolong", "inc.prolong", "m.hatch", "n5", "n9")) #manually re-orders stages.

prl.long$timept<-prl.long$stage #create numerical "timept" variable for ordering stages
levels(prl.long$timept)<-c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18") #rename levels in bulk! saves lines of code. 
prl.long$timept<-as.numeric(prl.long$timept) #continuous, numerical variable for x axis

#focal variable indicates time points I care about specifically 
prl.long$focal<-prl.long$timept
prl.long$focal<-ifelse(prl.long$stage %in% c("bldg", "inc.d3", "m.inc.d8", "inc.d9", "hatch"), "y", "n") #if the stage is in the list of accepted values, focal is yes, otherwise, no. 

prl.long$log.exp<-log(prl.long$counts) #log transform counts data 

```

```{r hyp plots}
bp.hyp.prl<- prl.long%>% filter(focal=="y" & tissue=="hypothalamus" & geneid=="prl") %>%
  ggplot(aes(y = log.exp, x = as.factor(timept)))+
  geom_point(aes(shape=sex, color=sex), position=position_jitter(width=0.1, height=0.1), size=3, alpha=1)+
  geom_boxplot(outlier.shape=NA, alpha=0)+ #no outliers because points plotted by geom_points
  scale_color_manual(values=c("purple3","salmon1"))+
  scale_x_discrete(labels=c("bldg", "inc.d3", "inc.d9", "m.inc.d8",  "hatch"))+
  scale_y_continuous(limits=c(3,7))+ #added so that both HYP graphs have same y axis
  labs(x=NULL,y="log(estimated counts)", title="Hypothalamus PRL")+
  theme_classic()+
  theme(text = element_text(size=16),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1))
print(bp.hyp.prl)

bp.hyp.prlr<- prl.long%>% filter(focal=="y" & tissue=="hypothalamus" & geneid=="prlr") %>%
  ggplot(aes(y = log.exp, x = as.factor(timept)))+
  geom_point(aes(shape=sex, color=sex), position=position_jitter(width=0.1, height=0.1), size=3, alpha=1)+
  geom_boxplot(outlier.shape=NA, alpha=0.25)+
  scale_color_manual(values=c("purple3","salmon1"))+
  scale_x_discrete(labels=c("bldg", "inc.d3", "inc.d9", "m.inc.d8",  "hatch"))+
  scale_y_continuous(limits=c(3,7))+ #added so that both HYP graphs have same y axis
  labs(x=NULL,y="log(estimated counts)", title="Hypothalamus PRLR")+
  theme_classic()+
  theme(text = element_text(size=16),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1))
print(bp.hyp.prlr)
```
```{r pit plots}
#PIT PRL  
bp.pit.prl<- prl.long%>% filter(focal=="y" & tissue=="pituitary" & geneid=="prl") %>%
  ggplot(aes(y = log.exp, x = as.factor(timept)))+
  geom_point(aes(shape=sex, colour=sex), position=position_jitter(width=0.1, height=0.1), size=3, alpha=1)+
  geom_boxplot(outlier.shape=NA, alpha=0.25)+
  scale_color_manual(values=c("purple3","salmon1"))+
  scale_y_continuous(limits=c(7,14))+
  scale_x_discrete(labels=c("bldg", "inc.d3", "inc.d9", "m.inc.d8",  "hatch"))+
  labs(x=NULL,y="log(estimated counts)", title="Pit PRL")+
  theme_classic()+
  theme(text = element_text(size=16),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1))

bp.pit.prlr<- prl.long%>% filter(focal=="y" & tissue=="pituitary" & geneid=="prlr") %>%
  ggplot(aes(y = log.exp, x = as.factor(timept)))+
  geom_point(aes(shape=sex,colour=sex), position=position_jitter(width=0.1, height=0.1), size=3, alpha=1)+
  geom_boxplot(outlier.shape=NA, alpha=0.25)+
  scale_color_manual(values=c("purple3","salmon1"))+
    theme(axis.text=element_text(size=22),
        axis.title=element_text(size=24,face="bold"),
        plot.caption = element_text(size=10, hjust=0),
        legend.position="none")+
  scale_x_discrete(labels=c("bldg", "inc.d3", "inc.d9", "m.inc.d8",  "hatch"))+
  scale_y_continuous(limits=c(3,7))+ #same limits as HYP PRLR graph
  labs(x=NULL,y="log(estimated counts)", title="Pit PRLR")+
  theme_classic()+
  theme(text = element_text(size=16),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1))

print(bp.pit.prl)
print(bp.pit.prlr)
```

```{r gonad plots}
#this is the only organ with log data plotted
#the only organ with special distinctive lines for manipulation
#GONAD PRL  
gp<-prl.long %>% 
  filter(focal=="y" & tissue=="gonad" & geneid=="prl") %>%
  group_by(timept) %>%
  summarise(avg_exp = mean(log.exp, na.rm = TRUE)) 
gnd.prl<-gp %>%
  ggplot(aes(x = timept, y = avg_exp)) +
    geom_point(aes(x=timept, y=log.exp, color=sex, fill=sex), data = prl.long %>% filter(tissue=="gonad" & geneid=="prl" & focal=="y"),inherit.aes = FALSE,size =4, alpha  =0.75, pch=21)+ scale_fill_manual(values=c("mediumpurple2","sienna1")) + scale_color_manual(values=c("mediumpurple2","sienna4"))+ 
    geom_line(col="grey43", size=1, alpha=1) + 
    geom_line(data = gp[gp$timept >="6" & gp$timept <="7",], 
              aes(x = timept, y = avg_exp),color="red", size = 1) + #adds a distinctive line for manipulation
    scale_x_continuous(breaks=c(2,3,4,6,7,9,11), labels=c("bldg", "lay", "inc.d3", "inc.d9", "m.inc.d8",  "inc.d17", "hatch"))+ 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    labs(title="Gonad ePRL") +
    theme_minimal()

#GONAD PRLR
gr<-prl.long %>% 
  filter(focal=="y" & tissue=="gonad" & geneid=="prlr") %>%
  group_by(timept) %>%
  summarise(avg_exp = mean(log.exp, na.rm = TRUE)) 
gnd.prlr<-gr %>%
  ggplot(aes(x = timept, y = avg_exp)) +
    geom_point(aes(x=timept, y=log.exp, color=sex, fill=sex), data = prl.long %>% filter(tissue=="gonad" & geneid=="prlr" & focal=="y"),inherit.aes = FALSE,size =4, alpha  =0.75, pch=21)+ scale_fill_manual(values=c("mediumpurple2","sienna1")) + scale_color_manual(values=c("mediumpurple2","sienna4"))+ 
    geom_line(col="grey43", size=1, alpha=1) + 
    geom_line(data = gr[gp$timept >="6" & gr$timept <="7",], 
              aes(x = timept, y = avg_exp),color="red", size = 1) + #adds a distinctive line for manipulation
    scale_x_continuous(breaks=c(2,3,4,6,7,9,11), labels=c("bldg", "lay", "inc.d3", "inc.d9", "m.inc.d8",  "inc.d17", "hatch"))+ 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    labs(title="Gonad PRLR") +
    theme_minimal()

print(gnd.prl)
print(gnd.prlr)
```
```{r crop data import, echo=FALSE}
crops<-read.csv(file="~/Documents/2018-04-16_PRLR_project_results.csv")
myvars<-c("ID","Stage","Sex","PRL_ddCT", "PRLR_ddCT") #variables I want to keep from csv
crops<-crops[myvars] #subsets dataframe
crops.long<-crops %>% gather(key="gene", value="ddCT", 4:5, factor_key=TRUE)#wide to long
crops.long$Stage <- factor(crops.long$Stage, levels=c("Bldg", "Inc_D3", "Inc_D9","Manip_D8", "Hatch")) #manually re-orders stages.
crops.long$timept<-crops.long$Stage #create numerical "timept" variable for ordering stages
levels(crops.long$timept)<-c("1","2","3","4","5") #rename levels in bulk! saves lines of code.

#log transform
crops.long$log.exp<-log((crops.long$ddCT)+13) #add 13 to make all values positive, then log transform
```

```{r crop plots}
bp.crop.prl<- crops.long%>% filter(gene=="PRL_ddCT") %>%
  ggplot(aes(y = -(ddCT), x = as.factor(timept)))+
  geom_point(aes(shape=Sex, colour=Sex), position=position_jitter(width=0.1, height=0.1), size=3, alpha=1)+
  geom_boxplot(outlier.shape=NA, alpha=0.25)+
  scale_color_manual(values=c("purple3","salmon1"))+
    theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        plot.caption = element_text(size=10, hjust=0),
        legend.position="none")+
  scale_x_discrete(labels=c("bldg", "inc.d3", "inc.d9", "m.inc.d8",  "hatch"))+
  labs(x=NULL,y="relative expression (ddCT)", title="Crop PRL")+
  scale_y_continuous(limits=c(-10,10))+ #same y axis between crop graphs
  theme_classic()+
  theme(text = element_text(size=16),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1))

bp.crop.prlr<- crops.long%>% filter(gene=="PRLR_ddCT") %>%
  ggplot(aes(y = -(ddCT), x = as.factor(timept)))+
  geom_point(aes(shape=Sex, colour=Sex), position=position_jitter(width=0.1, height=0.1), size=3, alpha=1)+
  geom_boxplot(outlier.shape=NA, alpha=0.25)+
  scale_color_manual(values=c("purple3","salmon1"))+
    theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        plot.caption = element_text(size=10, hjust=0),
        legend.position="none")+
  scale_x_discrete(labels=c("bldg", "inc.d3", "inc.d9", "m.inc.d8",  "hatch"))+
  labs(x=NULL,y="relative expression (ddCT)", title="Crop PRLR")+
  scale_y_continuous(limits=c(-10,10))+ #same y axis between crop graphs 
  theme_classic()+
  theme(text = element_text(size=16),
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle=45, hjust=1))

print(bp.crop.prl)
print(bp.crop.prlr)
```


```{r original plot code, eval=FALSE, echo=FLASE}

#PLOTS BELOW WORK!####
#next:change ggplot dimensions for poster.

pit.avg<-prl.long %>% filter(focal=="y" & tissue=="pituitary" & geneid=="prl") %>%
    group_by(timept) %>%
    summarise(avg_exp = mean(counts, na.rm = TRUE))

 p1<-pit.avg %>% 
  ggplot(aes(x = timept, y = avg_exp)) +
  geom_point(aes(x=timept, y=counts, color=sex), data = prl.long %>% filter(tissue=="pituitary" & geneid=="prl" & focal=="y"),inherit.aes = FALSE,size =3, alpha  =0.75)+ scale_color_manual(values=c("mediumpurple2","sienna1"))+
  geom_line(col="gray", size=1, alpha=1) + #order matters, brings line to front
  scale_x_continuous(breaks=c(2,3,4,6,9,11), labels=c("bldg", "lay", "inc.d3", "m.inc.d8",  "inc.d17", "hatch"))+ #labels continuous x axis with stages
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(title="PIT PRL") +
  theme_minimal()

ggsave("pit_prl.png", plot = last_plot(), width=11, height=1.5, units="in", dpi=320)
```

```{r histograms, eval=FALSE}
#huge amounts of outliers!
#histogram of prl expression by tissue 
#heavy right skew, especially in pituitary
prl.long %>% filter(geneid=="prl") %>%
ggplot(aes(x=counts)) + 
    geom_histogram(data=subset(prl.long,tissue=="hypothalamus"),fill = "red", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="pituitary"),fill = "blue", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="gonad"),fill = "green", alpha = 0.2) + 
    xlim(0,2500) #does not remove outliers, but limits their influence on the plot 

#histogram of prlr expression by tissue
#similar pattern, heavy right skew esp. in pit
prl.long %>% filter(geneid=="prlr") %>%
ggplot(aes(x=counts)) + 
    geom_histogram(data=subset(prl.long,tissue=="hypothalamus"),fill = "red", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="pituitary"),fill = "blue", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="gonad"),fill = "green", alpha = 0.2) +
    xlim(0,2000)

prl.long$log.exp<-log(prl.long$counts) #log transform counts data 

#look at distributions given the log transformed counts 

prl.long %>% filter(geneid=="prl") %>%  #PRL
ggplot(aes(x=log.exp)) + 
    geom_histogram(data=subset(prl.long,tissue=="hypothalamus"),fill = "red", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="pituitary"),fill = "blue", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="gonad"),fill = "green", alpha = 0.2) 
#bimodal distribution in pituitary PRL

prl.long %>% filter(geneid=="prlr") %>%  #PRLR
ggplot(aes(x=log.exp)) + 
    geom_histogram(data=subset(prl.long,tissue=="hypothalamus"),fill = "red", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="pituitary"),fill = "blue", alpha = 0.2) +
    geom_histogram(data=subset(prl.long,tissue=="gonad"),fill = "green", alpha = 0.2)
#bimodal distribution in pituitary PRL - is this an artifact of log transformation?

```
```{r line plots comparing expression levels}
#how can you put these two graphs together?
all.prl<-prl.long %>% filter(focal=="y") %>%
  group_by(tissue,timept)%>%
  summarize(avg_exp=mean(log.exp, na.rm = TRUE)) %>%
  ggplot(aes(x=timept, y=avg_exp, color=tissue))+
  geom_line(size=1, alpha=1)
print(all.prl)


prl.long<-mutate(prl.long,
   tissxgene = paste(tissue, geneid,sep = ' ')) #creates the tissxgene value

all.genes<-prl.long %>% filter(focal=="y" & tissue!= "gonad") %>%
  group_by(tissxgene, timept)%>%
  summarize(avg_exp=mean(log.exp, na.rm = TRUE)) %>%
  ggplot(aes(x=timept, y=avg_exp, color=tissxgene, linetype=tissxgene))+
  geom_line(size=1, alpha=1)+
  scale_x_continuous(breaks=c(2,3,4,6,9,11), labels=c("bldg", "lay", "inc.d3", "m.inc.d8",  "inc.d17", "hatch"))+
  scale_linetype_manual(values=c("longdash", "solid","longdash","solid"))+
  scale_color_manual(values=c("turquoise2", "turquoise4","salmon1","salmon3"))+
  labs(y="log(estimated counts)", x="parental care stage")+
  theme_minimal()
print(all.genes + theme(legend.position="bottom"))
```

```{r lm hyp}

#HYP PRL
hprl<-prl.long %>% filter(tissue=="hypothalamus" & geneid=="prl" & focal=="y")
m.hprl<- glm(log.exp~stage*sex, data=hprl, family="gaussian")
anova(m.hprl, test="Chisq")
#only an effect of stage on Hyp PRL, no interaction or sex effect. 
summary(glm(log.exp~stage, data=hprl, family="gaussian"))  #model with only stage
#post hoc only for stage
pairs(lsmeans(m.hprl, ~ stage)) #contrasts with "mvt" method and Bonferroni correction
#yet...results reported as Tukey method

#HYP PRLR
hprlr<-prl.long %>% filter(tissue=="hypothalamus" & geneid=="prlr" & focal=="y")
m.hprlr<- glm(log.exp~stage*sex, data=hprlr, family="gaussian")
anova(m.hprlr, test="Chisq")
#significant effect of stage and sex, but NO interaction
summary(glm(log.exp~stage+sex, data=hprlr, family="gaussian")) #only m.inc.d8 signif. 
pairs(lsmeans(m.hprlr, ~ stage)) #females less than males #Tukey method 
pairs(lsmeans(m.hprlr, ~ sex)) #contrasts with "mvt" method and Bonferroni correction
rbind((pairs(lsmeans(m.hprlr, ~ stage | sex))),(pairs(lsmeans(m.hprlr, ~ sex | stage))))
```
```{r lm pit}
#ANOVAs to start, lots of significance....
prl.long$bird_id<-as.factor(prl.long$bird_id)
pprl<-prl.long %>% filter(tissue=="pituitary" & geneid=="prl" & focal=="y")
m.pprl<- glm(log.exp~stage*sex, data=pprl, family="gaussian")
anova(m.pprl, test="Chisq") #effect of stage and sex, but no interaction 
pairs(lsmeans(m.pprl, ~stage))
pairs(lsmeans(m.pprl, ~sex))#females higher than males
rbind((pairs(lsmeans(m.pprl, ~ stage | sex))),(pairs(lsmeans(m.pprl, ~ sex | stage)))) #contrasts with "mvt" method and Bonferroni correction


prl.long$bird_id<-as.factor(prl.long$bird_id)
pprlr<-prl.long %>% filter(tissue=="pituitary" & geneid=="prlr" & focal=="y")
m.pprlr<- glm(log.exp~stage*sex, data=pprlr, family="gaussian")
anova(m.pprlr, test="Chisq") #effect of SEX only. no interaction
pairs(lsmeans(m.pprlr, ~sex))#females lower than males 

```
```{r lm crops}
cprl<-crops.long %>% filter(gene=="PRL_ddCT")
m.cprl<- glm((-ddCT)~Stage*Sex, data=cprl, family="gaussian")
anova(m.cprl, test="Chisq") #trend only towards effect of Sex. 
m.cprl.sex<-glm((-ddCT)~Sex, data=cprl, family="gaussian")
anova(m.cprl.sex, test="Chisq")
pairs(lsmeans(m.cprl.sex, ~Sex))#females lower than males 

cprlr<-crops.long %>% filter(gene=="PRLR_ddCT")
m.cprlr<- glm((-ddCT)~Stage*Sex, data=cprlr, family="gaussian")
anova(m.cprlr, test="Chisq") #effect of Stage only, not sex. 
pairs(lsmeans(m.cprlr, ~Stage))#females lower than males 
```

```{r send to ppt, echo=FALSE}
#Sends all boxplots to powerpoint
read_pptx() %>% 
add_slide(layout = "Title and Content", master = "Office Theme") %>% 
ph_with_vg(code = print(bp.hyp.prl), type="body", bg = "transparent") %>%
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
ph_with_vg(code = print(bp.hyp.prlr), type="body", bg = "transparent") %>%
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
ph_with_vg(code = print(bp.pit.prl), type="body", bg = "transparent") %>%
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
ph_with_vg(code = print(bp.pit.prlr), type="body", bg = "transparent") %>%
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
ph_with_vg(code = print(bp.crop.prl), type="body", bg = "transparent") %>%
    add_slide(layout = "Title and Content", master = "Office Theme") %>% 
ph_with_vg(code = print(bp.crop.prlr), type="body", bg = "transparent") %>%
print(target = "~/Desktop/charts.pptx") %>% 
invisible()

```

#what are all my NAs in this plot?
https://github.com/Cyranka/rviz/blob/master/tidy_tuesday_week_28/create_graphs.R#L50

Re-naming levels in bulk: https://stackoverflow.com/questions/29711067/how-to-change-name-of-factor-levels
Lsmeans constrast code from: 
https://stats.stackexchange.com/questions/165125/lsmeans-r-adjust-for-multiple-comparisons-with-interaction-terms
And grouping contrasts by letter https://www.researchgate.net/post/How_to_perform_Grouping_of_Pairwise_comparison_obtained_after_Tukey_Test_One_way_ANOVA

```
